import "./hero.css";
import { Link } from "react-router-dom";

function Hero() {
  return (
    <section className="hero">
      <div className="hero-content">
        <h1>Welcome to our AI Art Gallery</h1>
        <p>
          Discover a new era of creativity where art meets artificial
          intelligence.
        </p>
        <p>
          Immerse yourself in a world where stunning artworks are crafted by
          cutting-edge AI algorithms, pushing the boundaries of imagination and
          innovation.
        </p>
        <Link to="/gallery" className="btn">
          Explore Gallery
        </Link>
      </div>
      <div className="hero-art">
        <img
          src="images/background.png"
          alt="an abstract background generated by AI"
          className="blurry-background"
        />
      </div>
    </section>
  );
}

export default Hero;
